import fs from "node:fs";
import os from "node:os";
import path from "node:path";

// Installs the `cerul-video-search` skill (generated by the local API) into a
// local agent's skills directory. The renderer fetches the generated files
// from `GET /v1/agent/skill` and hands them to the main process to write.

export type AgentConnectTargetId = "claude-code" | "codex";

export type AgentSkillFilePayload = {
  path: string;
  content: string;
};

export type AgentConnectSkillState = {
  installed: boolean;
  version?: string;
};

export type AgentConnectDetection = {
  id: AgentConnectTargetId;
  detected: boolean;
  skill: AgentConnectSkillState;
};

export const SKILL_DIR_NAME = "cerul-video-search";

const TARGET_BASE_DIRS: Record<AgentConnectTargetId, () => string> = {
  "claude-code": () => path.join(os.homedir(), ".claude"),
  codex: () => path.join(os.homedir(), ".codex"),
};

function isTargetId(value: unknown): value is AgentConnectTargetId {
  return value === "claude-code" || value === "codex";
}

function skillDirFor(target: AgentConnectTargetId | undefined, baseDir: string | undefined): string {
  if (baseDir) {
    if (!path.isAbsolute(baseDir)) {
      throw new Error("baseDir must be an absolute path");
    }
    return path.join(baseDir, SKILL_DIR_NAME);
  }
  if (!target || !isTargetId(target)) {
    throw new Error("unknown agent target");
  }
  return path.join(TARGET_BASE_DIRS[target](), "skills", SKILL_DIR_NAME);
}

function readSkillState(skillDir: string): AgentConnectSkillState {
  const manifest = path.join(skillDir, "SKILL.md");
  let content: string;
  try {
    content = fs.readFileSync(manifest, "utf8");
  } catch {
    return { installed: false };
  }
  const version = /^\s*version:\s*(\S+)\s*$/m.exec(content)?.[1];
  return { installed: true, version };
}

export function detectAgentTargets(): AgentConnectDetection[] {
  return (Object.keys(TARGET_BASE_DIRS) as AgentConnectTargetId[]).map((id) => {
    const base = TARGET_BASE_DIRS[id]();
    let detected = false;
    try {
      detected = fs.statSync(base).isDirectory();
    } catch {
      detected = false;
    }
    return {
      id,
      detected,
      skill: readSkillState(path.join(base, "skills", SKILL_DIR_NAME)),
    };
  });
}

export function installAgentSkill(args: {
  target?: AgentConnectTargetId;
  baseDir?: string;
  files: AgentSkillFilePayload[];
}): AgentConnectSkillState {
  const files = Array.isArray(args.files) ? args.files : [];
  if (files.length === 0 || !files.some((file) => file.path === "SKILL.md")) {
    throw new Error("skill bundle must contain SKILL.md");
  }
  const skillDir = skillDirFor(args.target, args.baseDir);
  for (const file of files) {
    const resolved = path.resolve(skillDir, file.path);
    if (resolved !== skillDir && !resolved.startsWith(skillDir + path.sep)) {
      throw new Error(`unsafe skill file path: ${file.path}`);
    }
  }
  fs.rmSync(skillDir, { recursive: true, force: true });
  for (const file of files) {
    const resolved = path.resolve(skillDir, file.path);
    fs.mkdirSync(path.dirname(resolved), { recursive: true });
    fs.writeFileSync(resolved, file.content, "utf8");
  }
  return readSkillState(skillDir);
}

export function uninstallAgentSkill(args: {
  target?: AgentConnectTargetId;
  baseDir?: string;
}): AgentConnectSkillState {
  const skillDir = skillDirFor(args.target, args.baseDir);
  // Only remove directories that actually look like our skill.
  if (fs.existsSync(skillDir) && !fs.existsSync(path.join(skillDir, "SKILL.md"))) {
    throw new Error("refusing to remove a directory that is not the Cerul skill");
  }
  fs.rmSync(skillDir, { recursive: true, force: true });
  return { installed: false };
}
